/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_HW_TREZOR_MESSAGES_COMMON_MESSAGES_COMMON_PB_H_INCLUDED
#define PB_HW_TREZOR_MESSAGES_COMMON_MESSAGES_COMMON_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _hw_trezor_messages_common_Failure_FailureType {
    hw_trezor_messages_common_Failure_FailureType_Failure_UnexpectedMessage = 1,
    hw_trezor_messages_common_Failure_FailureType_Failure_ButtonExpected = 2,
    hw_trezor_messages_common_Failure_FailureType_Failure_DataError = 3,
    hw_trezor_messages_common_Failure_FailureType_Failure_ActionCancelled = 4,
    hw_trezor_messages_common_Failure_FailureType_Failure_PinExpected = 5,
    hw_trezor_messages_common_Failure_FailureType_Failure_PinCancelled = 6,
    hw_trezor_messages_common_Failure_FailureType_Failure_PinInvalid = 7,
    hw_trezor_messages_common_Failure_FailureType_Failure_InvalidSignature = 8,
    hw_trezor_messages_common_Failure_FailureType_Failure_ProcessError = 9,
    hw_trezor_messages_common_Failure_FailureType_Failure_NotEnoughFunds = 10,
    hw_trezor_messages_common_Failure_FailureType_Failure_NotInitialized = 11,
    hw_trezor_messages_common_Failure_FailureType_Failure_PinMismatch = 12,
    hw_trezor_messages_common_Failure_FailureType_Failure_FirmwareError = 99
} hw_trezor_messages_common_Failure_FailureType;
#define _hw_trezor_messages_common_Failure_FailureType_MIN hw_trezor_messages_common_Failure_FailureType_Failure_UnexpectedMessage
#define _hw_trezor_messages_common_Failure_FailureType_MAX hw_trezor_messages_common_Failure_FailureType_Failure_FirmwareError
#define _hw_trezor_messages_common_Failure_FailureType_ARRAYSIZE ((hw_trezor_messages_common_Failure_FailureType)(hw_trezor_messages_common_Failure_FailureType_Failure_FirmwareError+1))

typedef enum _hw_trezor_messages_common_ButtonRequest_ButtonRequestType {
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_Other = 1,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_FeeOverThreshold = 2,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_ConfirmOutput = 3,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_ResetDevice = 4,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_ConfirmWord = 5,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_WipeDevice = 6,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_ProtectCall = 7,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_SignTx = 8,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_FirmwareCheck = 9,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_Address = 10,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_PublicKey = 11,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_MnemonicWordCount = 12,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_MnemonicInput = 13,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_PassphraseType = 14,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_UnknownDerivationPath = 15,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_RecoveryHomepage = 16,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_Success = 17,
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_Warning = 18
} hw_trezor_messages_common_ButtonRequest_ButtonRequestType;
#define _hw_trezor_messages_common_ButtonRequest_ButtonRequestType_MIN hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_Other
#define _hw_trezor_messages_common_ButtonRequest_ButtonRequestType_MAX hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_Warning
#define _hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ARRAYSIZE ((hw_trezor_messages_common_ButtonRequest_ButtonRequestType)(hw_trezor_messages_common_ButtonRequest_ButtonRequestType_ButtonRequest_Warning+1))

typedef enum _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType {
    hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_PinMatrixRequestType_Current = 1,
    hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_PinMatrixRequestType_NewFirst = 2,
    hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_PinMatrixRequestType_NewSecond = 3
} hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType;
#define _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_MIN hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_PinMatrixRequestType_Current
#define _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_MAX hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_PinMatrixRequestType_NewSecond
#define _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_ARRAYSIZE ((hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType)(hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_PinMatrixRequestType_NewSecond+1))

/* Struct definitions */
typedef struct _hw_trezor_messages_common_ButtonAck {
    char dummy_field;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_ButtonAck) */
} hw_trezor_messages_common_ButtonAck;


typedef struct _hw_trezor_messages_common_PassphraseAck {
    pb_callback_t passphrase;
    pb_callback_t state;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_PassphraseAck) */
} hw_trezor_messages_common_PassphraseAck;


typedef struct _hw_trezor_messages_common_PassphraseStateAck {
    char dummy_field;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_PassphraseStateAck) */
} hw_trezor_messages_common_PassphraseStateAck;


typedef struct _hw_trezor_messages_common_PassphraseStateRequest {
    pb_callback_t state;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_PassphraseStateRequest) */
} hw_trezor_messages_common_PassphraseStateRequest;


typedef struct _hw_trezor_messages_common_PinMatrixAck {
    pb_callback_t pin;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_PinMatrixAck) */
} hw_trezor_messages_common_PinMatrixAck;


typedef struct _hw_trezor_messages_common_Success {
    pb_callback_t message;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_Success) */
} hw_trezor_messages_common_Success;


typedef struct _hw_trezor_messages_common_ButtonRequest {
    bool has_code;
    hw_trezor_messages_common_ButtonRequest_ButtonRequestType code;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_ButtonRequest) */
} hw_trezor_messages_common_ButtonRequest;


typedef struct _hw_trezor_messages_common_Failure {
    bool has_code;
    hw_trezor_messages_common_Failure_FailureType code;
    pb_callback_t message;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_Failure) */
} hw_trezor_messages_common_Failure;


typedef struct _hw_trezor_messages_common_HDNodeType {
    uint32_t depth;
    uint32_t fingerprint;
    uint32_t child_num;
    pb_callback_t chain_code;
    pb_callback_t private_key;
    pb_callback_t public_key;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_HDNodeType) */
} hw_trezor_messages_common_HDNodeType;


typedef struct _hw_trezor_messages_common_PassphraseRequest {
    bool has_on_device;
    bool on_device;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_PassphraseRequest) */
} hw_trezor_messages_common_PassphraseRequest;


typedef struct _hw_trezor_messages_common_PinMatrixRequest {
    bool has_type;
    hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType type;
/* @@protoc_insertion_point(struct:hw_trezor_messages_common_PinMatrixRequest) */
} hw_trezor_messages_common_PinMatrixRequest;


/* Initializer values for message structs */
#define hw_trezor_messages_common_Success_init_default {{{NULL}, NULL}}
#define hw_trezor_messages_common_Failure_init_default {false, _hw_trezor_messages_common_Failure_FailureType_MIN, {{NULL}, NULL}}
#define hw_trezor_messages_common_ButtonRequest_init_default {false, _hw_trezor_messages_common_ButtonRequest_ButtonRequestType_MIN}
#define hw_trezor_messages_common_ButtonAck_init_default {0}
#define hw_trezor_messages_common_PinMatrixRequest_init_default {false, _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_MIN}
#define hw_trezor_messages_common_PinMatrixAck_init_default {{{NULL}, NULL}}
#define hw_trezor_messages_common_PassphraseRequest_init_default {false, 0}
#define hw_trezor_messages_common_PassphraseAck_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define hw_trezor_messages_common_PassphraseStateRequest_init_default {{{NULL}, NULL}}
#define hw_trezor_messages_common_PassphraseStateAck_init_default {0}
#define hw_trezor_messages_common_HDNodeType_init_default {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define hw_trezor_messages_common_Success_init_zero {{{NULL}, NULL}}
#define hw_trezor_messages_common_Failure_init_zero {false, _hw_trezor_messages_common_Failure_FailureType_MIN, {{NULL}, NULL}}
#define hw_trezor_messages_common_ButtonRequest_init_zero {false, _hw_trezor_messages_common_ButtonRequest_ButtonRequestType_MIN}
#define hw_trezor_messages_common_ButtonAck_init_zero {0}
#define hw_trezor_messages_common_PinMatrixRequest_init_zero {false, _hw_trezor_messages_common_PinMatrixRequest_PinMatrixRequestType_MIN}
#define hw_trezor_messages_common_PinMatrixAck_init_zero {{{NULL}, NULL}}
#define hw_trezor_messages_common_PassphraseRequest_init_zero {false, 0}
#define hw_trezor_messages_common_PassphraseAck_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define hw_trezor_messages_common_PassphraseStateRequest_init_zero {{{NULL}, NULL}}
#define hw_trezor_messages_common_PassphraseStateAck_init_zero {0}
#define hw_trezor_messages_common_HDNodeType_init_zero {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define hw_trezor_messages_common_PassphraseAck_passphrase_tag 1
#define hw_trezor_messages_common_PassphraseAck_state_tag 2
#define hw_trezor_messages_common_PassphraseStateRequest_state_tag 1
#define hw_trezor_messages_common_PinMatrixAck_pin_tag 1
#define hw_trezor_messages_common_Success_message_tag 1
#define hw_trezor_messages_common_ButtonRequest_code_tag 1
#define hw_trezor_messages_common_Failure_code_tag 1
#define hw_trezor_messages_common_Failure_message_tag 2
#define hw_trezor_messages_common_HDNodeType_depth_tag 1
#define hw_trezor_messages_common_HDNodeType_fingerprint_tag 2
#define hw_trezor_messages_common_HDNodeType_child_num_tag 3
#define hw_trezor_messages_common_HDNodeType_chain_code_tag 4
#define hw_trezor_messages_common_HDNodeType_private_key_tag 5
#define hw_trezor_messages_common_HDNodeType_public_key_tag 6
#define hw_trezor_messages_common_PassphraseRequest_on_device_tag 1
#define hw_trezor_messages_common_PinMatrixRequest_type_tag 1

/* Struct field encoding specification for nanopb */
#define hw_trezor_messages_common_Success_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING, message, 1)
#define hw_trezor_messages_common_Success_CALLBACK pb_default_field_callback
#define hw_trezor_messages_common_Success_DEFAULT NULL

#define hw_trezor_messages_common_Failure_FIELDLIST(X, a) \
X(a, STATIC, OPTIONAL, UENUM, code, 1) \
X(a, CALLBACK, OPTIONAL, STRING, message, 2)
#define hw_trezor_messages_common_Failure_CALLBACK pb_default_field_callback
#define hw_trezor_messages_common_Failure_DEFAULT NULL

#define hw_trezor_messages_common_ButtonRequest_FIELDLIST(X, a) \
X(a, STATIC, OPTIONAL, UENUM, code, 1)
#define hw_trezor_messages_common_ButtonRequest_CALLBACK NULL
#define hw_trezor_messages_common_ButtonRequest_DEFAULT NULL

#define hw_trezor_messages_common_ButtonAck_FIELDLIST(X, a) \

#define hw_trezor_messages_common_ButtonAck_CALLBACK NULL
#define hw_trezor_messages_common_ButtonAck_DEFAULT NULL

#define hw_trezor_messages_common_PinMatrixRequest_FIELDLIST(X, a) \
X(a, STATIC, OPTIONAL, UENUM, type, 1)
#define hw_trezor_messages_common_PinMatrixRequest_CALLBACK NULL
#define hw_trezor_messages_common_PinMatrixRequest_DEFAULT NULL

#define hw_trezor_messages_common_PinMatrixAck_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING, pin, 1)
#define hw_trezor_messages_common_PinMatrixAck_CALLBACK pb_default_field_callback
#define hw_trezor_messages_common_PinMatrixAck_DEFAULT NULL

#define hw_trezor_messages_common_PassphraseRequest_FIELDLIST(X, a) \
X(a, STATIC, OPTIONAL, BOOL, on_device, 1)
#define hw_trezor_messages_common_PassphraseRequest_CALLBACK NULL
#define hw_trezor_messages_common_PassphraseRequest_DEFAULT NULL

#define hw_trezor_messages_common_PassphraseAck_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING, passphrase, 1) \
X(a, CALLBACK, OPTIONAL, BYTES, state, 2)
#define hw_trezor_messages_common_PassphraseAck_CALLBACK pb_default_field_callback
#define hw_trezor_messages_common_PassphraseAck_DEFAULT NULL

#define hw_trezor_messages_common_PassphraseStateRequest_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES, state, 1)
#define hw_trezor_messages_common_PassphraseStateRequest_CALLBACK pb_default_field_callback
#define hw_trezor_messages_common_PassphraseStateRequest_DEFAULT NULL

#define hw_trezor_messages_common_PassphraseStateAck_FIELDLIST(X, a) \

#define hw_trezor_messages_common_PassphraseStateAck_CALLBACK NULL
#define hw_trezor_messages_common_PassphraseStateAck_DEFAULT NULL

#define hw_trezor_messages_common_HDNodeType_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, UINT32, depth, 1) \
X(a, STATIC, REQUIRED, UINT32, fingerprint, 2) \
X(a, STATIC, REQUIRED, UINT32, child_num, 3) \
X(a, CALLBACK, REQUIRED, BYTES, chain_code, 4) \
X(a, CALLBACK, OPTIONAL, BYTES, private_key, 5) \
X(a, CALLBACK, OPTIONAL, BYTES, public_key, 6)
#define hw_trezor_messages_common_HDNodeType_CALLBACK pb_default_field_callback
#define hw_trezor_messages_common_HDNodeType_DEFAULT NULL

extern const pb_msgdesc_t hw_trezor_messages_common_Success_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_Failure_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_ButtonRequest_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_ButtonAck_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_PinMatrixRequest_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_PinMatrixAck_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_PassphraseRequest_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_PassphraseAck_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_PassphraseStateRequest_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_PassphraseStateAck_msg;
extern const pb_msgdesc_t hw_trezor_messages_common_HDNodeType_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define hw_trezor_messages_common_Success_fields &hw_trezor_messages_common_Success_msg
#define hw_trezor_messages_common_Failure_fields &hw_trezor_messages_common_Failure_msg
#define hw_trezor_messages_common_ButtonRequest_fields &hw_trezor_messages_common_ButtonRequest_msg
#define hw_trezor_messages_common_ButtonAck_fields &hw_trezor_messages_common_ButtonAck_msg
#define hw_trezor_messages_common_PinMatrixRequest_fields &hw_trezor_messages_common_PinMatrixRequest_msg
#define hw_trezor_messages_common_PinMatrixAck_fields &hw_trezor_messages_common_PinMatrixAck_msg
#define hw_trezor_messages_common_PassphraseRequest_fields &hw_trezor_messages_common_PassphraseRequest_msg
#define hw_trezor_messages_common_PassphraseAck_fields &hw_trezor_messages_common_PassphraseAck_msg
#define hw_trezor_messages_common_PassphraseStateRequest_fields &hw_trezor_messages_common_PassphraseStateRequest_msg
#define hw_trezor_messages_common_PassphraseStateAck_fields &hw_trezor_messages_common_PassphraseStateAck_msg
#define hw_trezor_messages_common_HDNodeType_fields &hw_trezor_messages_common_HDNodeType_msg

/* Maximum encoded size of messages (where known) */
/* hw_trezor_messages_common_Success_size depends on runtime parameters */
/* hw_trezor_messages_common_Failure_size depends on runtime parameters */
#define hw_trezor_messages_common_ButtonRequest_size 2
#define hw_trezor_messages_common_ButtonAck_size 0
#define hw_trezor_messages_common_PinMatrixRequest_size 2
/* hw_trezor_messages_common_PinMatrixAck_size depends on runtime parameters */
#define hw_trezor_messages_common_PassphraseRequest_size 2
/* hw_trezor_messages_common_PassphraseAck_size depends on runtime parameters */
/* hw_trezor_messages_common_PassphraseStateRequest_size depends on runtime parameters */
#define hw_trezor_messages_common_PassphraseStateAck_size 0
/* hw_trezor_messages_common_HDNodeType_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
