/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "messages-bitcoin.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(hw_trezor_messages_bitcoin_MultisigRedeemScriptType, hw_trezor_messages_bitcoin_MultisigRedeemScriptType, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_MultisigRedeemScriptType_HDNodePathType, hw_trezor_messages_bitcoin_MultisigRedeemScriptType_HDNodePathType, 2)


PB_BIND(hw_trezor_messages_bitcoin_GetPublicKey, hw_trezor_messages_bitcoin_GetPublicKey, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_PublicKey, hw_trezor_messages_bitcoin_PublicKey, 2)


PB_BIND(hw_trezor_messages_bitcoin_GetAddress, hw_trezor_messages_bitcoin_GetAddress, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_Address, hw_trezor_messages_bitcoin_Address, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_SignMessage, hw_trezor_messages_bitcoin_SignMessage, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_MessageSignature, hw_trezor_messages_bitcoin_MessageSignature, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_VerifyMessage, hw_trezor_messages_bitcoin_VerifyMessage, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_SignTx, hw_trezor_messages_bitcoin_SignTx, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_TxRequest, hw_trezor_messages_bitcoin_TxRequest, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_TxRequest_TxRequestDetailsType, hw_trezor_messages_bitcoin_TxRequest_TxRequestDetailsType, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_TxRequest_TxRequestSerializedType, hw_trezor_messages_bitcoin_TxRequest_TxRequestSerializedType, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_TxAck, hw_trezor_messages_bitcoin_TxAck, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_TxAck_TransactionType, hw_trezor_messages_bitcoin_TxAck_TransactionType, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_TxAck_TransactionType_TxInputType, hw_trezor_messages_bitcoin_TxAck_TransactionType_TxInputType, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_TxAck_TransactionType_TxOutputBinType, hw_trezor_messages_bitcoin_TxAck_TransactionType_TxOutputBinType, AUTO)


PB_BIND(hw_trezor_messages_bitcoin_TxAck_TransactionType_TxOutputType, hw_trezor_messages_bitcoin_TxAck_TransactionType_TxOutputType, AUTO)






/* @@protoc_insertion_point(eof) */
