/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "messages-common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(hw_trezor_messages_common_Success, hw_trezor_messages_common_Success, AUTO)


PB_BIND(hw_trezor_messages_common_Failure, hw_trezor_messages_common_Failure, AUTO)


PB_BIND(hw_trezor_messages_common_ButtonRequest, hw_trezor_messages_common_ButtonRequest, AUTO)


PB_BIND(hw_trezor_messages_common_ButtonAck, hw_trezor_messages_common_ButtonAck, AUTO)


PB_BIND(hw_trezor_messages_common_PinMatrixRequest, hw_trezor_messages_common_PinMatrixRequest, AUTO)


PB_BIND(hw_trezor_messages_common_PinMatrixAck, hw_trezor_messages_common_PinMatrixAck, AUTO)


PB_BIND(hw_trezor_messages_common_PassphraseRequest, hw_trezor_messages_common_PassphraseRequest, AUTO)


PB_BIND(hw_trezor_messages_common_PassphraseAck, hw_trezor_messages_common_PassphraseAck, AUTO)


PB_BIND(hw_trezor_messages_common_PassphraseStateRequest, hw_trezor_messages_common_PassphraseStateRequest, AUTO)


PB_BIND(hw_trezor_messages_common_PassphraseStateAck, hw_trezor_messages_common_PassphraseStateAck, AUTO)


PB_BIND(hw_trezor_messages_common_HDNodeType, hw_trezor_messages_common_HDNodeType, AUTO)






/* @@protoc_insertion_point(eof) */
